name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Force Xcode 13
      run: /usr/bin/xcrun --sdk macosx --show-sdk-platform-path/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -print-target-info
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
