name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Force Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
